routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CityController;
use App\Http\Controllers\StateController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [FrontendController::class, 'index'])->name('website');



Route::get('/front-category', [FrontendController::class, 'category'])->name('front.category');
Route::get('/front-category-show/{id}', [FrontendController::class, 'categoryShow']);
Route::get('/productDetails/{product?}/{slug?}', [FrontendController::class, 'productDetails']);
Route::Post('/add-to-cart', [CartController::class, 'addToCart']);
Route::get('/front', [CartController::class, 'showCart']);
Route::post('/cartDelete', [CartController::class, 'cartDelete']);
Route::post('/cartUpdate', [CartController::class, 'cartUpdate']);
Route::get('/checkout', [CheckoutController::class, 'index']);
Route::get('/placorder', [CheckoutController::class, 'placorder'])->name('placorder');

// user middleware route
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::get('my-order',[OrderController::class,'index'])->name('myOrder');
});

// admin route
 Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
     });
    Route::get('/category',[CategoryController::class,'index'])->name('category');
    Route::get('/categoryAdd',[CategoryController::class,'create'])->name('category.add');
    Route::post('/categorystore',[CategoryController::class,'store'])->name('category.store');
    Route::get('/categoryedit/{id}',[CategoryController::class,'edit'])->name('category.edit');
    Route::post('/categoryupdate',[CategoryController::class,'update']);
    Route::delete('/categorydelete/{id}',[CategoryController::class,'destroy'])->name('category.delete');
    Route::resource('/product', ProductController::class);

    //route for relation
    Route::get('/country',[CountryController::class,'index']);
    Route::get('/state',[StateController::class,'index']);
    Route::get('/city',[cityController::class,'index']);
    Route::get('/countryAdd',[CountryController::class,'create']);
    Route::get('/stateAdd',[StateController::class,'create']);
    Route::get('/cityAdd',[CityController::class,'create']);
    Route::post('/countryStore',[CountryController::class,'store'])->name('countryStore');
    Route::post('/stateStore',[StateController::class,'store'])->name('stateStore');
    Route::post('/cityStore',[CityController::class,'store'])->name('cityStore');
 });

Route::get('/clear', function(){
    \Artisan::call('route:clear');
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
});


Route::get('/productImage',function(){
    $data = \App\Models\Product::all();
    $id =172;
    foreach($data as $item){
        $item->image = "https://picsum.photos/id/".$id."/640/480.jpg";
        $item->update();
        $id++;
    }
    return $data;
});

Route::get('/catImage',function(){
    $data = \App\Models\Category::all();
    $id =172;
    foreach($data as $item){
        $item->image = "https://picsum.photos/id/".$id."/640/480.jpg";
        $item->update();
        $id++;
    }
    return $data;
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table = 'products';
    protected $fillable =[
        'category_id',
        'name',
        'small_description',
        'description',
        'original_price',
        'selling_price',
        'image',
        'qty',
        'tax',
        'status',
        'trending',
        'meta_title',
        'meta_keyword',
        'meta_description',
    ];
    public function category(){
        return $this->belongsTo(Category::class);
    }
//    public function cartItem(){
//        return $this->hasMany(OrderItem::class);
//    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;
use File;
use Session;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::query()->orderBy('id','DESC')->with('category')->get();
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::query()->get();
        return view('admin.product.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product();
        $product->name = $request->name;
        $product->slug = $request->name;
        $product->category_id = $request->category_id;
        $product->description = $request->description;
        $product->small_description = $request->small_description;
        $product->original_price = $request->original_price;
        $product->selling_price = $request->selling_price;
        $product->quantity = $request->quantity;
        $product->tax = $request->tax;
        $product->status = $request->status == TRUE ? '1' : '0';
        $product->trending = $request->trending == TRUE ? '1' : '0';
        $product->meta_title = $request->meta_title;
        $product->meta_description = $request->meta_description;
        $product->meta_keyword = $request->meta_keyword;
        if($request->file('image')){
            $file= $request->file('image');
            $filename='public/product/'.date('YmdHi').'.'.$file->getClientOriginalExtension();
            $file-> move(public_path('public/product'), $filename);
            $product['image']= $filename;
        }

        $product->save();
        Session::flash('status','Product Added Successfully');
        return redirect()->route('product.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::query()->get();
       return view('admin.product.edit',compact('product','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $product->name = $request->name;
        $product->slug = $request->name;
        $product->category_id = $request->category_id;
        $product->description = $request->description;
        $product->small_description = $request->small_description;
        $product->original_price = $request->original_price;
        $product->selling_price = $request->selling_price;
        $product->quantity = $request->quantity;
        $product->tax = $request->tax;
        $product->status = $request->status == TRUE ? '1' : '0';
        $product->trending = $request->trending == TRUE ? '1' : '0';
        $product->meta_title = $request->meta_title;
        $product->meta_description = $request->meta_description;
        $product->meta_keyword = $request->meta_keyword;
        if($request->file('new_image')){
            $file= $request->file('new_image');
            $filename='public/product/'.date('YmdHi').'.'.$file->getClientOriginalExtension();
            $file-> move(public_path('public/product'), $filename);
            $product['image']= $filename;
        }else{
            $product['image']= $product->image;
        }

        $product->update();
        Session::flash('status','Product Update Successfully');
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if ($product) {
            File::delete($product->image);
            $product->delete();
            Session::flash('status','Data Successfully Deleted');
            return redirect()->back();
          }
    }
}

resources/views/admin/product/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0">Category List</h1> -->
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Add Product</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">

                <form method="POST" action="{{ route('product.store') }}" enctype="multipart/form-data">
                    <div class="row">
                        @csrf
                        @method('POST')
                        @include('admin.product.form', ['button' => 'Save'])
                    </div>
                </form>

            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    </div>
    <div>
    @endsection

resources/views/admin/product/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0">Category List</h1> -->
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Edit Product</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">

                <form method="POST" action="{{ route('product.update',[$product->id])}}" enctype="multipart/form-data">
                    <div class="row">
                        @csrf
                        @method('PUT')
                        @include('admin.product.form', ['button' => 'Update'])
                    </div>
                </form>

            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    </div>
    <div>
    @endsection

resources/views/admin/product/form.blade.php
<div class="form-group col-md-6" style="border-right:1px solid #ddd;">
    <input type="hidden" name="id" value="{{isset($product) ? $product->id : ''}}">
    <label for="">Name</label>
    <input name="name" type="text" class="form-control" placeholder="Enter product name" style="border:none"
        value="{{ isset($product) ? $product->name : old('name') }}">
    @error('name')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>

    <select name="category_id" id="" class="form-control" style="width:100%">
        <option value="{{isset($product->category_id) ? $product->category_id : 'Select Category' }} " Seleced>{{isset($product->category_id) ? $product->category->name : 'Select Category' }}</option>
        @foreach($categories as $item)
        <option value="{{ $item->id}}">{{ $item->name}}</option>
        @endforeach
    </select>
    <hr>

    <label for="">Original Price</label>
    <input name="original_price" type="number" class="form-control" placeholder="Enter product original price"
        style="border:none" value="{{ isset($product) ? $product->original_price : old('original_price') }}">
    @error('original_price')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>

    <label for="">Selling Price</label>
    <input name="selling_price" type="number" class="form-control" placeholder="Enter product Sellign price"
        style="border:none" value="{{ isset($product) ? $product->selling_price : old('selling_price') }}">
    @error('selling_price')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>
    <label for="">Tax</label>
    <input name="tax" type="number" class="form-control" placeholder="Enter product tax" style="border:none"
        value="{{ isset($product) ? $product->tax : old('tax') }}">
    @error('tax')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>
    <label for="">Quantity</label>
    <input name="quantity" type="number" class="form-control" placeholder="Enter product quantity" style="border:none"
        value="{{ isset($product) ? $product->quantity : old('quantity') }}">
    @error('quantity')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>


    <label for="">Status</label>
    <input name="status" type="checkbox" @if (isset($product)) {{ $product->status == 1 ? 'checked' : '' }} @endif>
    <label for="">trending</label>
    <input name="trending" type="checkbox" class="" @if (isset($product)) {{ $product->trending ==1 ? 'checked' : '' }}
        @endif>
</div>
<div class="form-group col-md-6">

    <label for="">Description</label>
    <input name="description" type="text" class="form-control" placeholder="Enter product Description"
        style="border:none" value="{{ isset($product) ? $product->description : old('description') }}">
    @error('description')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>

    <label for="">Image : </label>

    @if(isset($product))
        @if (isset($product->image))
        if
            <img name="image" class="update_image formControl" src="{{asset($product->image)}}" alt="{{$product->image}}"
                height="100px" width="100px">
            <input name="new_image" type="file" style="border:none">
        @else
        else
            <input name="new_image" type="file" style="border:none">
        @endif
    @else
    <input name="image" type="file" style="border:none">
    @endif
    @error('image')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>

    <label for="">Small Description</label>
    <input name="small_description" type="text" class="form-control" placeholder="Enter product Samll Description"
        style="border:none" value="{{ isset($product) ? $product->small_description : old('small_description') }}">
    @error('small_description')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>



    <label for="">Meta Description</label>
    <input name="meta_description" type="text" class="form-control" placeholder="Enter product Meta Description"
        style="border:none" value="{{ isset($product) ? $product->meta_description : old('meta_description') }}">
    @error('meta_description')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>
    <label for="">Meta title</label>
    <input name="meta_title" type="text" class="form-control" placeholder="Enter product Meta title" style="border:none"
        value="{{ isset($product) ? $product->meta_title : old('meta_title') }}">
    @error('meta_title')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>

    <label for="">Meta Keyword</label>
    <input name="meta_keyword" type="text" class="form-control" placeholder="Enter product Meta keyword"
        style="border:none" value="{{ isset($product) ? $product->meta_keyword : old('meta_keyword') }}">
    @error('meta_keyword')
    <span class="text-danger">{{ $message }}</span>
    @enderror
    <hr>
</div>
<button type="submit" class="btn btn-primary">{{ $button }}</button>
<!-- <div class="card-body">
    <div class="form-group col-md-12">
        <label for="exampleInputname">Name</label>
        <input style="border:none;" type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter user Name"
            value="{{ isset($user) ? $user->name : old('name') }}">
        @error('name')
    <span class="text-danger">{{ $message }}</span>
@enderror
    </div>
    <hr>
    <div class="form-group">
        <label for="exampleInputname">Email</label>
        <input type="email" name="email" class="form-control" id="exampleInputName" placeholder="Enter user email"
            value="{{ isset($user) ? $user->email : old('email') }}">
        @error('email')
    <span class="text-danger">{{ $message }}</span>
@enderror
    </div>
    <div class="form-group">
        <label for="exampleInputname">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputName"
            placeholder="Enter user password" value="{{ isset($user) ? $user->password : old('password') }}">
        @error('password')
    <span class="text-danger">{{ $message }}</span>
@enderror
    </div>
    <div class="form-group">
        <label for="exampleInputname">Image</label>
        <input type="file" name="image" class="form-control" id="exampleInputName" placeholder="Enter user image"
            value="{{ isset($user) ? $user->image : old('image') }}">
        @error('image')
    <span class="text-danger">{{ $message }}</span>
@enderror
    </div>
    <div class="form-group">
        <label for="exampleInputDescription">Description</label>
        <textarea name="description" id="" cols="60" rows="4"
            class="form-control">{{ isset($user) ? $user->description : old('description') }}</textarea>
    </div>
</div>
<div class="card-footer">
    <button type="submit" class="btn btn-primary">{{ $button }}</button>
</div> -->

resources/views/admin/product/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Product List</h1>
            </div><!-- /.col -->

            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('product.index') }}">Home</a></li>
                    <li class="breadcrumb-item active"> <a href="{{ route('product.create') }}">add new category</a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card">
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered table-hover" >

                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Selling Price</th>
                    <th>Category</th>
                    <th>Quantity</th>
                    <th>Status</th>
                    <th>image</th>
                    <th>Action</th>
                </tr>

                @foreach ($products as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->original_price }}</td>
                    <td>{{ $item->selling_price }}</td>
                    <td> <span class="badge badge-primary" style="padding:5px;">{{ $item->category->name }}</span></td>
                    <td>{{ $item->quantity }}</td>
                    <td>{{ $item->status }}</td>
                    <td>
                        <img src="{{ $item->image }}" class="img-fluid cat-image" alt="{{ $item->image }}">
                    </td>
                    <td class="d-flex">
                        <a href="{{ route('product.edit', [$item->id]) }}" class="btn btn-sm btn-primary mr-1"><i
                                class="fas fa-edit"></i></a>
                        <form action="{{ route('product.destroy', [$item->id]) }}" class="mr-1" method="POST">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-sm btn-danger "><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach

            </table>
        </div>
        <!-- /.card-body -->
    </div>
</div>
<!-- /.card -->
</div>
<div>
    @endsection